options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 0
    - max-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: true
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 0
  no-vendor-prefixes:
    - 1
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - order:
        # based on SMACSS Property Order
        # http://smacss.com/book/formatting
        # Heading
        - content
        - quotes
        # Box
        - display
        - visibility
        - position
        - z-index
        - top
        - right
        - bottom
        - left
        - box-sizing
        - grid
        - grid-after
        - grid-area
        - grid-auto-columns
        - grid-auto-flow
        - grid-auto-rows
        - grid-before
        - grid-column
        - grid-column-end
        - grid-column-gap
        - grid-column-start
        - grid-columns
        - grid-end
        - grid-gap
        - grid-row
        - grid-row-end
        - grid-row-gap
        - grid-row-start
        - grid-rows
        - grid-start
        - grid-template
        - grid-template-areas
        - grid-template-columns
        - grid-template-rows
        - flex
        - flex-basis
        - flex-direction
        - flex-flow
        - flex-grow
        - flex-shrink
        - flex-wrap
        - align-content
        - align-items
        - align-self
        - justify-content
        - order
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - float
        - clear
        - overflow
        - overflow-x
        - overflow-y
        - clip
        - zoom
        - columns
        - column-gap
        - column-fill
        - column-rule
        - column-span
        - column-count
        - column-width
        - table-layout
        - empty-cells
        - caption-side
        - border-spacing
        - border-collapse
        - list-style
        - list-style-position
        - list-style-type
        - list-style-image
        # Animation
        - transform
        - transform-origin
        - transform-style
        - backface-visibility
        - perspective
        - perspective-origin
        - transition
        - transition-property
        - transition-duration
        - transition-timing-function
        - transition-delay
        - animation
        - animation-name
        - animation-duration
        - animation-play-state
        - animation-timing-function
        - animation-delay
        - animation-iteration-count
        - animation-direction
        # Border
        - border
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-width
        - border-top-width
        - border-right-width
        - border-bottom-width
        - border-left-width
        - border-style
        - border-top-style
        - border-right-style
        - border-bottom-style
        - border-left-style
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-left-radius
        - border-bottom-right-radius
        - border-color
        - border-top-color
        - border-right-color
        - border-bottom-color
        - border-left-color
        - outline
        - outline-color
        - outline-offset
        - outline-style
        - outline-width
        - stroke-width
        - stroke-linecap
        - stroke-dasharray
        - stroke-dashoffset
        - stroke
        # Background
        - opacity
        - background
        - background-color
        - background-image
        - background-repeat
        - background-position
        - background-size
        - box-shadow
        - fill
        # Text
        - color
        - font
        - font-family
        - font-size
        - font-size-adjust
        - font-stretch
        - font-effect
        - font-style
        - font-variant
        - font-weight
        - font-emphasize
        - font-emphasize-position
        - font-emphasize-style
        - letter-spacing
        - line-height
        - list-style
        - word-spacing
        - text-align
        - text-align-last
        - text-decoration
        - text-indent
        - text-justify
        - text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - text-rendering
        - text-outline
        - text-shadow
        - text-transform
        - text-wrap
        - word-wrap
        - word-break
        - text-emphasis
        - text-emphasis-color
        - text-emphasis-style
        - text-emphasis-position
        - vertical-align
        - white-space
        - word-spacing
        - hyphens
        - src
        # Other
        - tab-size
        - counter-reset
        - counter-increment
        - resize
        - cursor
        - pointer-events
        - speak
        - user-select
        - nav-index
        - nav-up
        - nav-right
        - nav-down
        - nav-left
    - ignore-custom-properties: false
  property-units:
    - 1
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}
  quotes:
    - 1
    - style: single
  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 1
